[package]
name = "omnicli-backup"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Core library component of the OmniCLI full-stack toolkit."
repository = "https://github.com/Manash07Bhoi/OmniCLI"



[dependencies]
omnicli-core = { path = "../omnicli-core" }

anyhow    = { workspace = true }
thiserror = { workspace = true }
serde     = { workspace = true }
serde_json = { workspace = true }
blake3    = { workspace = true }
walkdir   = { workspace = true }
chrono    = { workspace = true }
indicatif = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
